export const CATEGORY_DATA: Record<string, string[]> = {
    "Music": ["Concerts", "Open Mics & Jams", "Music Festivals", "Live Gigs", "Jams"],
    "Nightlife": ["Clubbing", "Karaoke Nights", "DJ Nights", "Parties"],
    "Social Mixers": ["Community Meetups"],
    "Performances": ["Dance", "Magic Shows", "Fashion Shows", "Literary", "Entertainment & Award Shows"],
    "Open Mics": ["Music Open Mics", "Comedy Open Mics", "Literary Open Mics"],
    "TV Screenings": ["Cricket Screenings", "Football Screenings", "F1 Screenings", "Movie Screenings", "Olympics Screenings", "Concert Screenings"],
    "Expos": ["Career Fairs", "Trade Shows", "Auto Expos", "Tech Expos", "Startup Expos"],
    "Comedy": ["Standup", "Improv", "Roast"],
    "Celebrations": ["NYE", "Christmas", "Diwali", "Holi", "Navratri", "Valentine's Day", "Father's Day", "Mother's Day", "Pongal", "Poila Baisakh", "Women's Day", "Lohri", "Pride Month", "Durga Puja", "Halloween"],
    "Fitness Activities": ["Pilates", "Rock Climbing", "Yoga", "Zumba", "Community Runs", "Gymnastics"],
    "Sports": ["Cricket Matches", "Football Matches", "Hockey Matches", "Tennis Matches", "Badminton Matches", "Basketball Matches", "Kho-Kho Matches", "Motorsport Matches", "Boxing Matches", "MMA Matches", "Padel Matches", "Chess Matches", "Athletics", "Kabaddi Matches", "Baseball Matches", "Pickleball Matches", "Wrestling Matches"],
    "Conferences & Talks": ["Tech Conferences & Talks", "Healthcare Conferences & Talks", "Marketing Conferences & Talks", "Business Conferences & Talks", "Education Conferences & Talks", "Music Conferences & Talks", "History Conferences & Talks", "Literature Conferences & Talks"],
    "Kids": ["Kids festival"],
    "Art Exhibitions": ["Artist Showcase", "Art Galleries", "Art Installations", "Immersive Art", "Photography Exhibits"],
    "Pet Activities": ["Pet Playdates", "Yoga with Pets", "Paint with Pets", "Brunch with Pets"],
    "Theme Parks": ["Trampoline Parks", "Snow Parks", "Entertainment Parks", "Adventure Parks"],
    "Game Zones": ["Go Karting", "Laser Tag", "Paintball", "Bowling", "Arcades", "Mystery Rooms", "Rage Rooms", "VR Rooms", "Escape Rooms", "Skating Arenas"],
    "Kids Play": ["Play Areas", "Kids Theme Parks"],
    "Adventure": ["Treks", "Hiking", "Skydiving", "Surfing", "Paragliding", "Beach Activities", "River Rafting", "Ziplining"],
    "Museums": ["History Museums", "Science Museums", "Art Museums", "Planetariums", "Music Museums", "Archaeological Museums", "Illusion Museums", "Wax Museums"],
    "Walks": ["City Walks", "Food Walks", "Heritage Walks"],
    "Workshops": ["Art & Craft Workshops", "Pottery Workshops", "Photography Workshops", "Culinary Workshops", "Writing Workshops", "Music Workshops", "Dance Workshops", "Acting Workshops", "Public Speaking Workshops", "Fashion & Beauty Workshops", "Finance Workshops", "Entrepreneurship Workshops", "Design Workshops", "DIY Workshops", "Languages Workshops", "Wellness Workshops", "Martial Arts Workshops", "Motorsport Workshops", "Tech Workshops", "Filmmaking Workshops"],
    "Play Sports": ["Cricket", "Football", "Pickleball", "Padel", "Badminton", "Tennis", "Squash", "Swimming", "Chess", "Golf", "Basketball"],
    "Food & Drinks": ["Pub Crawl", "Gourmet Experiences", "Pop Ups", "Beverage Tastings", "Community Dining", "Picnics"],
    "Water Parks": [],
    "Esports": [],
    "Games & Quizzes": ["Board Games & Puzzles", "Trivia Nights & Quizzes", "Treasure Hunts"],
    "Summer Camps": [],
    "Sip & Paint": [],
    "Attractions": ["Aquariums", "Zoos"],
    "Fitness Events": ["Marathons", "Triathlons", "Cycling", "Crossfit", "Fitness & Wellness Fests"],
    "Pet Events": ["Pet Carnivals", "Pet Shows", "Pet Adoption Drives", "Pet Wellness Camps"],
    "Fests & Fairs": ["Literary Fests", "Pop Culture Fairs", "Food & Beverage Fests", "Flea Markets", "Art Fairs", "Craft Bazaars", "Film & Theatre Fests", "Carnivals"],
    "Play": [],
    "Travel": ["Sightseeing", "Camping", "Wildlife", "Day Trips", "Weekend Getaways", "Stargazing", "Cruises", "Landmarks", "Safaris", "Tours"]
};

export const CATEGORIES = Object.keys(CATEGORY_DATA);

export const CITIES = [
    "Abohar", "Abu Road", "Achalpur", "Adilabad", "Adoni", "Agartala", "Agra", "Ahilyanagar", "Ahmedabad", "Airoli",
    "Aizawl", "Ajmer", "Akola", "Akot", "Alandur", "Alappuzha", "Aligarh", "Alipur Duar", "Allinagaram", "Alwar",
    "Amalapuram", "Amalner", "Amaravati", "Ambajogai", "Ambala", "Ambala Sadar", "Ambarnath", "Ambattur", "Ambikapur", "Ambur",
    "Amravati", "Amreli", "Amritsar", "Amroha", "Amur", "Anaiyur", "Anakapalle", "Anand", "Anantapur", "Anantnag",
    "Anjangaon", "Anjar", "Ankleshwar", "Aonla", "Arakkonam", "Arambagh", "Araria", "Arcot", "Arni", "Arrah",
    "Arsikere", "Aruppukkottai", "Arwal", "Asansol", "Ashoknagar", "Ashoknagar Kalyangarh", "Ashta", "Attili", "Attur", "Auraiya",
    "Aurangabad", "Avadi", "Avaniyapuram", "Ayodhya", "Azamgarh", "Bada Barabil", "Badagara", "Badlapur", "Badvel", "Bagaha",
    "Bagalkot", "Bagbera", "Bahadurgarh", "Baharampur", "Baheri", "Bahraigh", "Baidyabati", "Balaghat", "Balangir", "Balasore",
    "Bali", "Ballari", "Ballarpur", "Balotra", "Balrampur", "Balurghat", "Banda", "Bangaon", "Bangarda Chhota", "Bankra",
    "Bankura", "Bansbaria", "Banswara", "Bapatla", "Baprola", "Barakpur", "Baramati", "Baramula", "Baran", "Baranagar",
    "Barasat", "Barauni", "Baraut", "Barbil", "Barddhaman", "Bardoli", "Bareilly", "Bargarh", "Barh", "Bari",
    "Baripada", "Barmer", "Barnala", "Barshi", "Baruipur", "Baruni", "Barwani", "Basavakalyan", "Basirhat City", "Basmat",
    "Basoda", "Basti", "Batala", "Bathinda", "Bawana", "Beawar", "Beed", "Begampur", "Begusarai", "Bela",
    "Belagavi", "Bellampalli", "Bengaluru", "Benipur", "Bettiah", "Betul", "Beypore", "Bhabhua", "Bhadohi", "Bhadrachalam",
    "Bhadrak", "Bhadravati", "Bhadreswar", "Bhagalpur", "Bhalswa Jahangirpur", "Bhandara", "Bharatpur", "Bharuch", "Bhatapara", "Bhatpara",
    "Bhavnagar", "Bhawanipatna", "Bhayandar", "Bhetia", "Bhilai", "Bhilai Charoda", "Bhilwara", "Bhimavaram", "Bhimunipatnam", "Bhind",
    "Bhiwadi", "Bhiwandi", "Bhiwani", "Bhongir", "Bhopal", "Bhubaneswar", "Bhuj", "Bhusawal", "Bidar", "Bihar Sharif",
    "Bihat", "Bijnor", "Bikaner", "Bilaspur", "Bilimora", "Bina", "Birgaon", "Bisalpur", "Bishnupur", "Biswan",
    "Bobbili", "Bodhan", "Bodinayakkanur", "Bokaro", "Bolpur", "Bongaigaon", "Borivli", "Borsad", "Botad", "Brahmapur",
    "Brajarajnagar", "Budaun", "Budge Budge", "Bulandshahr", "Buldana", "Bundi", "Burari", "Burhanpur", "Buxar", "Byasanagar",
    "Chaibasa", "Chakradharpur", "Chalisgaon", "Challakere", "Chamrajnagar", "Chanda", "Chandannagar", "Chandigarh", "Chandpur", "Chanduasi",
    "Changanacheri", "Channapatna", "Chapra", "Charkhi Dadri", "Chas", "Chaumu", "Chengalpattu", "Chennai", "Cheruvannur", "Chhatarpur",
    "Chhibramau", "Chhindwara", "Chidambaram", "Chik Ballapur", "Chikhli", "Chikmagalur", "Chilakalurupet", "Chilla Soroda Bangar", "Chinnachowk", "Chintamani",
    "Chiplun", "Chirala", "Chirmiri", "Chitradurga", "Chittoor", "Chittorgarh", "Chopda", "Choudwar", "Churu", "Closepet",
    "Coimbatore", "Contai", "Cuddalore", "Cumbum", "Cuttack", "Dabhel", "Dabhoi", "Dabra", "Dabwali", "Dadri",
    "Dahanu", "Dalupura", "Dam Dam", "Damoh", "Dandeli", "Darbhanga", "Darjiling", "Datia", "Daudnagar", "Dausa",
    "Davangere", "Deesa", "Deglur", "Dehradun", "Delhi", "Delhi Cantonment", "Deoband", "Deoghar", "Deolali", "Deoli",
    "Deoria", "Devakottai", "Dewas", "Dhamtari", "Dhanbad", "Dhar", "Dharapuram", "Dharashiv", "Dharavi", "Dharmapuri",
    "Dharmavaram", "Dhaulpur", "Dhenkanal", "Dholka", "Dhone", "Dhoraji", "Dhrangadhra", "Dhubri", "Dhule", "Dhulian",
    "Dhuri", "Dibrugarh", "Didwana", "Dimapur", "Dinapore", "Dinapur Nizamat", "Dindigul", "Diphu", "Doddaballapura", "Dohad",
    "Dombivali", "Dumraon", "Durg", "Durgapur", "Edattala", "Electronic City Phase I", "Eluru", "Emmiganur", "Erode", "Etah",
    "Etawa", "Etawah", "Faridabad", "Faridkot", "Faridpur", "Farrukhabad", "Fatehabad", "Fatehpur", "Fatwa", "Fazilka",
    "Firozabad", "Firozpur", "Forbesganj", "Fyzabad", "Gadag", "Gadag-Betageri", "Gaddi Annaram", "Gadwal", "Gajraula", "Gajuwaka",
    "Gandhidham", "Gandhinagar", "Gangapur", "Gangarampur", "Gangavati", "Gangoh", "Gangtok", "Garhchiroli", "Gaya", "Gharroli",
    "Ghatal", "Ghaziabad", "Ghazipur", "Giridih", "Goalpara", "Gobichettipalayam", "Gobindgarh", "Godhra", "Gohad", "Gohana",
    "Gokak", "Gokalpur", "Gola Gokarannath", "Gonda City", "Gondal", "Gondia", "Gopalganj", "Gorakhpur", "Goyerkata", "Greater Noida",
    "Gudivada", "Gudiyatham", "Gudur", "Gumla", "Guna", "Gundupalaiyam", "Guntakal", "Guntur", "Gurdaspur", "Gurugram",
    "Guwahati", "Gwalior", "Gyanpur", "Habra", "Hajipur", "Haldia", "Haldwani", "Halisahar", "Halol", "Hansi",
    "Hanumangarh", "Hapur", "Harda", "Hardoi", "Haridwar", "Harihar", "Hasanpur", "Hashtsal", "Hassan", "Hathras",
    "Haveri", "Hazaribagh", "Hilsa", "Himatnagar", "Hindaun", "Hindupur", "Hinganghat", "Hingoli", "Hiriyur", "Hisar",
    "Hodal", "Hosapete", "Hoshiarpur", "Hoskote", "Hosur", "Howrah", "Hubballi", "Hugli", "Hunsur", "Hyderabad",
    "Ichalkaranji", "Idaiyarpalaiyam", "Idappadi", "Ilkal", "Imphal", "Indore", "Islampur", "Itanagar", "Itarsi", "Jabalpur",
    "Jafarabad", "Jagadhri", "Jagdalpur", "Jaggaiahpet", "Jagraon", "Jagtial", "Jahanabad", "Jahangirabad", "Jaigaon", "Jaipur",
    "Jaisalmer", "Jaitpur", "Jalandhar", "Jalaun", "Jalgaon", "Jalna", "Jalor", "Jalpaiguri", "Jamalpur", "Jamkhandi",
    "Jammu", "Jamnagar", "Jamshedpur", "Jamui", "Jamuria", "Jangaon", "Jangipur", "Jaora", "Jatani", "Jaunpur",
    "Jetpur", "Jeypore", "Jhalawar", "Jhansi", "Jhargram", "Jharia", "Jharsuguda", "Jhumri Telaiya", "Jhunjhunun", "Jind",
    "Jodhpur", "Jorhat", "Junagadh", "Kadapa", "Kadayanallur", "Kadi", "Kadiri", "Kagaznagar", "Kairana", "Kaithal",
    "Kakinada", "Kalaburagi", "Kalamassery", "Kaliyaganj", "Kallakurichi", "Kalna", "Kalol", "Kalyan", "Kalyani", "Kamareddi",
    "Kamarhati", "Kamthi", "Kanakapura", "Kanayannur", "Kanchipuram", "Kanchrapara", "Kandi", "Kandukur", "Kanhangad", "Kannauj",
    "Kannur", "Kanpur", "Kapas Herd", "Kapurthala Town", "Karad", "Karaikal", "Karaikkudi", "Karanja", "Karauli", "Karawalnagar",
    "Karimganj", "Karimnagar", "Karnal", "Karol Bagh", "Karur", "Karwar", "Kasaragod", "Kasganj", "Kashipur", "Kasibugga",
    "Kasipalaiyam", "Kathua", "Katihar", "Katoya", "Katras", "Kavali", "Kavanur", "Kayamkulam", "Keonjhargarh", "Keshod",
    "Khadki", "Khagaul", "Khajoori Khas", "Khambhat", "Khamgaon", "Khammam", "Khanapuram Haveli", "Khandwa", "Khanna", "Kharagpur",
    "Kharakvasla", "Kharar", "Khardah", "Kharghar", "Khargone", "Khatauli", "Khopoli", "Khurai", "Khurja", "Kirari Sulemannagar",
    "Kiratpur", "Kishanganj", "Kishangarh", "Koch Bihar", "Kochi", "Kodar", "Kodungallur", "Kohima", "Kolar", "Kolhapur",
    "Kolkata", "Kollam", "Kollegal", "Konch", "Konnagar", "Kopargaon", "Koppal", "Koratla", "Korba", "Kosi",
    "Kota", "Kotharia", "Kotkapura", "Kot Kapura", "Kottagudem", "Kottayam", "Kovilpatti", "Koyilandy", "Kozhikode", "Krishnagiri",
    "Krishnanagar", "Kuchaman", "Kukatpally", "Kulti", "Kumarapalayam", "Kumbakonam", "Kundla", "Kuniyamuttur", "Kunnamkulam", "Kurichchi",
    "Kurnool", "Kushinagar", "Ladnun", "Laharpur", "Lakhimpur", "Lal Bahadur Nagar", "Lalitpur", "Latur", "Laxmangarh", "Lohardaga",
    "Lonavla", "Loni", "Luckeesarai", "Lucknow", "Ludhiana", "Lunglei", "Macherla", "Machilipatnam", "Madanapalle", "Madgaon",
    "Madhavaram", "Madhepura", "Madhubani", "Madhupur", "Madhurampur Dehri", "Madhyamgram", "Madurai", "Maduravoyal", "Mahasamund", "Mahbubnagar",
    "Mahesana", "Maheshtala", "Mahoba", "Mahuva", "Mainpuri", "Makrana", "Malappuram", "Malda", "Malegaon", "Maler Kotla",
    "Malkajgiri", "Malkapur", "Malout", "Mancherial", "Mandamarri", "Mandapeta", "Mandi Dabwali", "Mandideep", "Mandla", "Mandoli",
    "Mandsaur", "Mandvi", "Mandya", "Mangalagiri", "Mangaluru", "Mango", "Mangrol", "Manjeri", "Manmad", "Mannarakkat",
    "Mannargudi", "Mansa", "Maraimalainagar", "Markapur", "Masaurhi Buzurg", "Mathura", "Mau", "Mawana", "Mawlai-Mawiong", "Mayiladuthurai",
    "Medininagar", "Medinipur", "Meerut", "Metpalle", "Mettupalayam", "Mettur", "Mhow", "Miryalaguda", "Mirzapur", "Mithepur",
    "Modasa", "Moga", "Mohali", "Mokameh", "Molarband", "Moonniyur", "Moradabad", "Morena", "Mormugao", "Morvi",
    "Mothihari", "Mubarakpur", "Mudhol", "Mughal Sarai", "Mukandpur", "Muktsar", "Mulbagal", "Mulugu", "Mumbai", "Mundka",
    "Munger", "Munnar", "Muradnagar", "Murwara", "Mustafabad", "Muzaffarnagar", "Muzaffarpur", "Mysuru", "Nabha", "Nadiad",
    "Nagaon", "Nagapattinam", "Nagari", "Nagaur", "Nagda", "Nagercoil", "Nagina", "Nagpur", "Naihati", "Najafgarh",
    "Najibabad", "Naksalbari", "Nalgonda", "Nallur", "Namakkal", "Nanded", "Nandurbar", "Nandyal", "Nangloi Jat", "Nanjangud",
    "Narasapur", "Narasaraopet", "Narela", "Narmadapuram", "Narnaul", "Narsimhapur", "Narwana", "Nashik", "Nasirabad", "Navadwip",
    "Navi Mumbai", "Navsari", "Nawabganj", "Nawada", "Nawalgarh", "Naya Gaon", "Nedumangad", "Neelankarai", "Nellore", "Nerkunram",
    "Nerupperichchal", "New Delhi", "Neyveli", "Neyyattinkara", "Nimach", "Nimbahera", "Nipani", "Nirmal", "Nithari", "Nizamabad",
    "Noida", "Nokha", "North Lakhimpur", "Nowrangapur", "Nuzvid", "Obra", "Okha", "Ongole", "Ooty", "Orai",
    "Ottapalam", "Ozar", "Pachora", "Palakkad", "Palakollu", "Palani", "Palanpur", "Palasa", "Palghar", "Pali",
    "Palitana", "Pallavaram", "Pallichal", "Palmaner", "Paloncha", "Palwal", "Palwancha", "Pammal", "Panchkula", "Pandharpur",
    "Panihati", "Panipat", "Panipat Taraf Makhdum Zadgan", "Panjim", "Panna", "Panruti", "Panvel", "Paradip Garh", "Paralakhemundi", "Paramagudi",
    "Parbhani", "Parli Vaijnath", "Parvatipuram", "Patan", "Pathankot", "Patiala", "Patna", "Pattukkottai", "Payyanur", "Peranampattu",
    "Periya Semur", "Petlad", "Phagwara", "Phaltan", "Phulwari Sharif", "Phusro", "Piduguralla", "Pilibhit", "Pilkhua", "Pimpri",
    "Pimpri-Chinchwad", "Pithampur", "Pithapuram", "Pollachi", "Ponnani", "Ponnur", "Ponnuru", "Poonamalle", "Porbandar", "Port Blair",
    "Prayagraj", "Proddatur", "Puducherry", "Pudukkottai", "Pulivendla", "Puliyankudi", "Pul Pehlad", "Punasa", "Pune", "Punganuru",
    "Puri", "Purnia", "Puruliya", "Pusad", "Puth Kalan", "Puttur", "Quthbullapur", "Rabkavi", "Rabkavi-Banhatti", "Raebareli",
    "Raghogarh", "Raichur", "Raiganj", "Raigarh", "Raipur", "Rajamahendravaram", "Rajapalayam", "Rajgangpur", "Rajgarh", "Rajkot",
    "Raj-Nandgaon", "Rajpura", "Rajpur Sonarpur", "Rajsamand", "Ramagundam", "Ramanathapuram", "Ramapuram", "Ramgarh", "Ramgundam", "Ramnagar",
    "Rampur", "Rampura Phul", "Rampur Hat", "Ranaghat", "Ranchi", "Ranebennur", "Raniganj", "Ranipet", "Rasapudipalem", "Rasipuram",
    "Ratangarh", "Rath", "Ratlam", "Ratnagiri", "Raurkela Industrial Township", "Raxaul", "Rayachoti", "Rayadrug", "Rayagada", "Razampeta",
    "Renukut", "Repalle", "Rewa", "Rewari", "Rishikesh", "Rishra", "Robertsonpet", "Roha", "Rohini", "Rohtak",
    "Roorkee", "Ropar", "Roshanpura", "Rourkela", "Rudrapur", "Sadatpur Gujran", "Sagar", "Saharanpur", "Saharsa", "Sahaswan",
    "Sahibabad Daulotpur", "Sahibganj", "Salem", "Salur", "Samalkot", "Samana", "Samastipur", "Sambalpur", "Sambhal", "Sanand",
    "Sandila", "Sangamner", "Sangareddi", "Sangli", "Sangrur", "Sankarankovil", "Sardarshahr", "Sarni", "Sasaram", "Satara",
    "Satna", "Sattenapalle", "Saugor", "Saunda", "Savarkundla", "Sawai Madhopur", "Secunderabad", "Sehore", "Sendhwa", "Seoni",
    "Serilingampalle", "Shahabad", "Shahada", "Shahdol", "Shahjanpur", "Shahpur", "Shahuwadi", "Shajapur", "Shamli", "Shantipur",
    "Shegaon", "Sheikhpura", "Shella", "Sheopur", "Sherkot", "Shikohabad", "Shillong", "Shimla", "Shirpur", "Shivaji Nagar",
    "Shivamogga", "Shivpuri", "Sholapur", "Shorapur", "Shrirampur", "Shujalpur", "Shyamnagar", "Sibsagar", "Siddhapur", "Siddipet",
    "Sidhi", "Sidlaghatta", "Sihor", "Sikandarabad", "Sikar", "Silchar", "Siliguri", "Sillod", "Silvassa", "Sindhnur",
    "Singrauli", "Sinnar", "Sira", "Sirhind", "Sironj", "Sirsa", "Sirsi", "Sirsilla", "Siruguppa", "Sitamarhi",
    "Sitapur", "Siuri", "Sivakasi", "Siwan", "Sonipat", "Sopur", "Soyibug", "Sri Dungargarh", "Sri Ganganagar", "Srikakulam",
    "Srikalahasti", "Srinagar", "Srivilliputhur", "Sujangarh", "Sultanganj", "Sultanpur", "Sultan Pur Majra", "Sunabeda", "Sunam", "Supaul",
    "Surat", "Suratgarh", "Surendranagar", "Suriapet", "Tadepalle", "Tadepalligudem", "Tadpatri", "Taj Pul", "Talegaon Dabhade", "Taliparamba",
    "Tambaram", "Tanda", "Tandoni", "Tandur", "Tanuku", "Tarn Taran", "Teghra", "Tellicherry", "Teni", "Tennala",
    "Tezpur", "Thane", "Thanesar", "Thanjavur", "Thenali", "Thenkasi", "Thiruvananthapuram", "Thiruvarur", "Thodupuzha", "Thoothukudi",
    "Thrissur", "Tikamgarh", "Tilhar", "Tindivanam", "Tinsukia", "Tiptur", "Tiruchengode", "Tiruchirappalli", "Tirumangalam", "Tirunelveli",
    "Tirupati", "Tirupattur", "Tirupparangunram", "Tiruppur", "Tirur", "Tirurangadi", "Tiruttangal", "Tiruvalla", "Tiruvallur", "Tiruvannamalai",
    "Tiruvottiyur", "Titagarh", "Tohana", "Tonk", "Tripunittura", "Tumkur", "Tundla", "Tuni", "Tura", "Udaipur",
    "Udgir", "Udhampur", "Udumalaippettai", "Udupi", "Ujhani", "Ujjain", "Ulhasnagar", "Ullagaram", "Ullal", "Uluberiya",
    "Umred", "Una", "Unjha", "Unnao", "Upleta", "Uppal Kalan", "Urun-Islampur", "Vadodara", "Valparai", "Valsad",
    "Vaniyambadi", "Vapi", "Varanasi", "Vasco da Gama", "Vazhakkala", "Vejalpur", "Velampalaiyam", "Vellore", "Venkatagiri", "Veraval",
    "Vidisha", "Vijalpor", "Vijayapura", "Vijayawada", "Vikarabad", "Villupuram", "Vinukonda", "Viramgam", "Virapandi", "Virappanchathiram",
    "Virar", "Viraraghavapuram", "Virudhachalam", "Virudunagar", "Visakhapatnam", "Visnagar", "Vizianagaram", "Vriddhachalam", "Vrindavan", "Wadgaon Kolhati",
    "Wani", "Wanparti", "Warangal", "Wardha", "Wari", "Washim", "Wokha", "Yadgir", "Yamuna Nagar", "Yanam",
    "Yavatmal", "Yelahanka", "Zahirabad", "Zerakpur", "Ziauddin Pur"
];
