/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutPreviewRouteImport } from './routes/layout-preview'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLayoutBuilderRouteImport } from './routes/_authenticated/layout-builder'

const LayoutPreviewRoute = LayoutPreviewRouteImport.update({
  id: '/layout-preview',
  path: '/layout-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutBuilderRoute =
  AuthenticatedLayoutBuilderRouteImport.update({
    id: '/layout-builder',
    path: '/layout-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/layout-preview': typeof LayoutPreviewRoute
  '/layout-builder': typeof AuthenticatedLayoutBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/layout-preview': typeof LayoutPreviewRoute
  '/layout-builder': typeof AuthenticatedLayoutBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/layout-preview': typeof LayoutPreviewRoute
  '/_authenticated/layout-builder': typeof AuthenticatedLayoutBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/layout-preview' | '/layout-builder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/layout-preview' | '/layout-builder'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/layout-preview'
    | '/_authenticated/layout-builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LayoutPreviewRoute: typeof LayoutPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/layout-preview': {
      id: '/layout-preview'
      path: '/layout-preview'
      fullPath: '/layout-preview'
      preLoaderRoute: typeof LayoutPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/layout-builder': {
      id: '/_authenticated/layout-builder'
      path: '/layout-builder'
      fullPath: '/layout-builder'
      preLoaderRoute: typeof AuthenticatedLayoutBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLayoutBuilderRoute: typeof AuthenticatedLayoutBuilderRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLayoutBuilderRoute: AuthenticatedLayoutBuilderRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LayoutPreviewRoute: LayoutPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
